In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,r2_score

In [2]:
df = pd.read_csv('HeartDisease.csv')
df

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,Male,Atypical angina,140,221,Lower than 120 mg/ml,ST-T wave abnormality,164,Yes,0.0,Downsloping,Zero,Fixed Defect,1
1021,60,Male,Typical angina,125,258,Lower than 120 mg/ml,Normal,141,Yes,2.8,Flat,One,Reversable Defect,0
1022,47,Male,Typical angina,110,275,Lower than 120 mg/ml,Normal,118,Yes,1.0,Flat,One,Fixed Defect,0
1023,50,Female,Typical angina,110,254,Lower than 120 mg/ml,Normal,159,No,0.0,Downsloping,Zero,Fixed Defect,1
1024,54,Male,Typical angina,120,188,Lower than 120 mg/ml,ST-T wave abnormality,113,No,1.4,Flat,One,Reversable Defect,0

In [3]:
df.columns

Index(['age', 'sex', 'chest_pain_type', 'resting_blood_pressure',
       'cholestoral', 'fasting_blood_sugar', 'rest_ecg', 'Max_heart_rate',
       'exercise_induced_angina', 'oldpeak', 'slope',
       'vessels_colored_by_flourosopy', 'thalassemia', 'target'],
      dtype='object')

In [4]:
df.isnull().sum()

age                              0
sex                              0
chest_pain_type                  0
resting_blood_pressure           0
cholestoral                      0
fasting_blood_sugar              0
rest_ecg                         0
Max_heart_rate                   0
exercise_induced_angina          0
oldpeak                          0
slope                            0
vessels_colored_by_flourosopy    0
thalassemia                      0
target                           0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1025 non-null   int64
 1   sex                            1025 non-null   object
 2   chest_pain_type                1025 non-null   object
 3   resting_blood_pressure         1025 non-null   int64
 4   cholestoral                    1025 non-null   int64
 5   fasting_blood_sugar            1025 non-null   object
 6   rest_ecg                       1025 non-null   object
 7   Max_heart_rate                 1025 non-null   int64
 8   exercise_induced_angina        1025 non-null   object
 9   oldpeak                        1025 non-null   float64
 10  slope                          1025 non-null   object
 11  vessels_colored_by_flourosopy  1025 non-null   object
 12  thalassemia                    1025 non-null   object
 13  target                         1025 non-null   int64
dtypes: float64(1), int64(5), object(8)
memory usage: 112.2+ KB

In [6]:
df.describe()

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,target
count,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000
mean,54.434146,131.611707,246.00000,149.114146,1.071512,0.513171
std,9.072290,17.516718,51.59251,23.005724,1.175053,0.500070
min,29.000000,94.000000,126.00000,71.000000,0.000000,0.000000
25%,48.000000,120.000000,211.00000,132.000000,0.000000,0.000000
50%,56.000000,130.000000,240.00000,152.000000,0.800000,1.000000
75%,61.000000,140.000000,275.00000,166.000000,1.800000,1.000000
max,77.000000,200.000000,564.00000,202.000000,6.200000,1.000000

In [7]:
df.rename(columns={
    'chest_pain_type' : 'CP-type',
    'resting_blood_pressure' : 'Resting-BP',
    'fasting_blood_sugar' : 'Fasting-BS',
    'rest_ecg':'Rest_ECG',
    'Max_heart_rate':'Max-HR',
    'exercise_included_angina':'CP-PhysicalActivitiy'
},inplace=True)

In [8]:
df

,age,sex,CP-type,Resting-BP,cholestoral,Fasting-BS,Rest_ECG,Max-HR,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,Male,Atypical angina,140,221,Lower than 120 mg/ml,ST-T wave abnormality,164,Yes,0.0,Downsloping,Zero,Fixed Defect,1
1021,60,Male,Typical angina,125,258,Lower than 120 mg/ml,Normal,141,Yes,2.8,Flat,One,Reversable Defect,0
1022,47,Male,Typical angina,110,275,Lower than 120 mg/ml,Normal,118,Yes,1.0,Flat,One,Fixed Defect,0
1023,50,Female,Typical angina,110,254,Lower than 120 mg/ml,Normal,159,No,0.0,Downsloping,Zero,Fixed Defect,1
1024,54,Male,Typical angina,120,188,Lower than 120 mg/ml,ST-T wave abnormality,113,No,1.4,Flat,One,Reversable Defect,0

# NOTE: ONE HOT Encoding for features

In [9]:
df['slope'].value_counts()

slope
Flat           482
Downsloping    469
Upsloping       74
Name: count, dtype: int64

In [10]:
df['sex'] = df['sex'].map({
    'Female': 1,
    'Male': 0
})

In [11]:
df['Fasting-BS'] = df['Fasting-BS'].map({
    'Lower than 120 mg/ml':0,
    'Greater than 120 mg/ml':1
})

In [12]:
df['thalassemia'].value_counts()

thalassemia
Fixed Defect         544
Reversable Defect    410
Normal                64
No                     7
Name: count, dtype: int64

In [13]:
df = pd.get_dummies(df, columns=['CP-type'])

In [14]:
df = pd.get_dummies(df, columns=['Rest_ECG'])

In [15]:
df['slope'] = df['slope'].map({
    'Upsloping':0,      #NOTE: generally less risky
    'Flat':1,           #NOTE: Intermediate
    'Downsloping':2
})

In [16]:
df['exercise_induced_angina'] = df['exercise_induced_angina'].map({
    'Yes':1,
    'No':0
})

In [17]:
df['vessels_colored_by_flourosopy'] = df['vessels_colored_by_flourosopy'].map({
    'Zero':0,
    'One':1,
    'Two':2,
    'Three':3
})

In [18]:
df = pd.get_dummies(df, columns=['thalassemia'])

In [19]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [20]:
df.shape

(1025, 22)

In [21]:
df = df.drop_duplicates()

In [22]:
df

,age,sex,Resting-BP,cholestoral,Fasting-BS,Max-HR,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,...,CP-type_Atypical angina,CP-type_Non-anginal pain,CP-type_Typical angina,Rest_ECG_Left ventricular hypertrophy,Rest_ECG_Normal,Rest_ECG_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,52,0,125,212,0,168,0,1.0,2,2.0,...,False,False,True,False,False,True,False,False,False,True
1,53,0,140,203,1,155,1,3.1,0,0.0,...,False,False,True,False,True,False,False,False,False,True
2,70,0,145,174,0,125,1,2.6,0,0.0,...,False,False,True,False,False,True,False,False,False,True
3,61,0,148,203,0,161,0,0.0,2,1.0,...,False,False,True,False,False,True,False,False,False,True
4,62,1,138,294,1,106,0,1.9,1,3.0,...,False,False,True,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,1,120,211,0,115,0,1.5,1,0.0,...,False,True,False,False,True,False,True,False,False,False
733,44,1,108,141,0,175,0,0.6,1,0.0,...,False,True,False,False,False,True,True,False,False,False
739,52,0,128,255,0,161,1,0.0,2,1.0,...,False,False,True,False,False,True,False,False,False,True
843,59,0,160,273,0,125,0,0.0,2,0.0,...,False,False,False,False,True,False,True,False,False,False
878,54,0,120,188,0,113,0,1.4,1,1.0,...,False,False,True,False,False,True,False,False,False,True

In [23]:
chunk1 = df.iloc[0:1,0:20]
chunk1

,age,sex,Resting-BP,cholestoral,Fasting-BS,Max-HR,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,target,CP-type_Asymptomatic,CP-type_Atypical angina,CP-type_Non-anginal pain,CP-type_Typical angina,Rest_ECG_Left ventricular hypertrophy,Rest_ECG_Normal,Rest_ECG_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_No
0,52,0,125,212,0,168,0,1.0,2,2.0,0,False,False,False,True,False,False,True,False,False

In [24]:
chunk2 = df.iloc[0:1,20:]
chunk2

   thalassemia_Normal  thalassemia_Reversable Defect
0               False                           True

In [25]:
df

,age,sex,Resting-BP,cholestoral,Fasting-BS,Max-HR,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,...,CP-type_Atypical angina,CP-type_Non-anginal pain,CP-type_Typical angina,Rest_ECG_Left ventricular hypertrophy,Rest_ECG_Normal,Rest_ECG_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,52,0,125,212,0,168,0,1.0,2,2.0,...,False,False,True,False,False,True,False,False,False,True
1,53,0,140,203,1,155,1,3.1,0,0.0,...,False,False,True,False,True,False,False,False,False,True
2,70,0,145,174,0,125,1,2.6,0,0.0,...,False,False,True,False,False,True,False,False,False,True
3,61,0,148,203,0,161,0,0.0,2,1.0,...,False,False,True,False,False,True,False,False,False,True
4,62,1,138,294,1,106,0,1.9,1,3.0,...,False,False,True,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,1,120,211,0,115,0,1.5,1,0.0,...,False,True,False,False,True,False,True,False,False,False
733,44,1,108,141,0,175,0,0.6,1,0.0,...,False,True,False,False,False,True,True,False,False,False
739,52,0,128,255,0,161,1,0.0,2,1.0,...,False,False,True,False,False,True,False,False,False,True
843,59,0,160,273,0,125,0,0.0,2,0.0,...,False,False,False,False,True,False,True,False,False,False
878,54,0,120,188,0,113,0,1.4,1,1.0,...,False,False,True,False,False,True,False,False,False,True

In [26]:
X = df

In [27]:
corr = df.corr()['target']
print(corr)

age                                     -0.221476
sex                                      0.283609
Resting-BP                              -0.146269
cholestoral                             -0.081437
Fasting-BS                              -0.026826
Max-HR                                   0.419955
exercise_induced_angina                 -0.435601
oldpeak                                 -0.429146
slope                                    0.343940
vessels_colored_by_flourosopy           -0.464357
target                                   1.000000
CP-type_Asymptomatic                     0.087959
CP-type_Atypical angina                  0.247649
CP-type_Non-anginal pain                 0.313696
CP-type_Typical angina                  -0.514626
Rest_ECG_Left ventricular hypertrophy   -0.068156
Rest_ECG_Normal                         -0.157299
Rest_ECG_ST-T wave abnormality           0.172827
thalassemia_Fixed Defect                 0.526030
thalassemia_No                          -0.007056
thalassemia_Normal                      -0.105986
thalassemia_Reversable Defect           -0.484887
Name: target, dtype: float64

In [28]:
selected_X = corr[abs(corr) > 0.1].index
selected_X

Index(['age', 'sex', 'Resting-BP', 'Max-HR', 'exercise_induced_angina',
       'oldpeak', 'slope', 'vessels_colored_by_flourosopy', 'target',
       'CP-type_Atypical angina', 'CP-type_Non-anginal pain',
       'CP-type_Typical angina', 'Rest_ECG_Normal',
       'Rest_ECG_ST-T wave abnormality', 'thalassemia_Fixed Defect',
       'thalassemia_Normal', 'thalassemia_Reversable Defect'],
      dtype='object')

In [29]:
selected_X = selected_X.to_list()
selected_X

['age',
 'sex',
 'Resting-BP',
 'Max-HR',
 'exercise_induced_angina',
 'oldpeak',
 'slope',
 'vessels_colored_by_flourosopy',
 'target',
 'CP-type_Atypical angina',
 'CP-type_Non-anginal pain',
 'CP-type_Typical angina',
 'Rest_ECG_Normal',
 'Rest_ECG_ST-T wave abnormality',
 'thalassemia_Fixed Defect',
 'thalassemia_Normal',
 'thalassemia_Reversable Defect']

In [30]:
selected_X.remove('target')
selected_X.remove('vessels_colored_by_flourosopy')

In [31]:
X = df[selected_X]
X

,age,sex,Resting-BP,Max-HR,exercise_induced_angina,oldpeak,slope,CP-type_Atypical angina,CP-type_Non-anginal pain,CP-type_Typical angina,Rest_ECG_Normal,Rest_ECG_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_Normal,thalassemia_Reversable Defect
0,52,0,125,168,0,1.0,2,False,False,True,False,True,False,False,True
1,53,0,140,155,1,3.1,0,False,False,True,True,False,False,False,True
2,70,0,145,125,1,2.6,0,False,False,True,False,True,False,False,True
3,61,0,148,161,0,0.0,2,False,False,True,False,True,False,False,True
4,62,1,138,106,0,1.9,1,False,False,True,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,1,120,115,0,1.5,1,False,True,False,True,False,True,False,False
733,44,1,108,175,0,0.6,1,False,True,False,False,True,True,False,False
739,52,0,128,161,1,0.0,2,False,False,True,False,True,False,False,True
843,59,0,160,125,0,0.0,2,False,False,False,True,False,True,False,False
878,54,0,120,113,0,1.4,1,False,False,True,False,True,False,False,True

In [32]:
y = df['target']

In [33]:
X_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [34]:
RC = RandomForestClassifier()

In [35]:
RC.fit(X_train,y_train)

RandomForestClassifier()

In [36]:
y_pred = RC.predict(x_test)

In [37]:
print(f"The accuracy of RandomForest model without hyperparameter tuning and cross validation is : {accuracy_score(y_test,y_pred)}")

The accuracy of RandomForest model without hyperparameter tuning and cross validation is : 0.7213114754098361

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
accuracy = np.mean(cross_val_score(RandomForestClassifier(),X,y,cv=18))
final_accuracy = accuracy.item()
final_accuracy
print(f"Accuracy with cross validation and without hyperparameter is {final_accuracy}")

Accuracy with cross validation and without hyperparameter is 0.7839052287581699

In [41]:
#NOTE: number of trees in a random forest
n_estimators = [20, 60, 100, 120]

In [42]:
#NOTE: number of features to consider at every split
max_features = [0.2, 0.6, 1.0]

In [58]:
param_dict = {
    'max_depth' : [2, 4, None],
    'max_features' : [4, 7, 12],
    'min_samples_split' : [3, 5],
    'bootstrap' : [True],       #NOTE: All values must be in list though a single variable 
    'max_samples' : [0.8]
}

In [59]:
RF = RandomForestClassifier(random_state=42)
from sklearn.model_selection import GridSearchCV
GridSearch = GridSearchCV(
    estimator = RF,
    param_grid=param_dict,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
GridSearch.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [2, 4, None],
                         'max_features': [4, 7, 12], 'max_samples': [0.8],
                         'min_samples_split': [3, 5]},
             scoring='accuracy')

In [62]:
print(GridSearch.best_params_)

{'bootstrap': True, 'max_depth': 4, 'max_features': 4, 'max_samples': 0.8, 'min_samples_split': 5}

In [65]:
print(GridSearch.best_score_)

0.8133503401360545