In [122]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [95]:
df = sns.load_dataset('penguins')

In [96]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [97]:
df['species'].describe()

count        344
unique         3
top       Adelie
freq         152
Name: species, dtype: object

In [98]:
print(df['species'].unique())

['Adelie' 'Chinstrap' 'Gentoo']

In [99]:
df = df.drop(columns=['bill_depth_mm', 'body_mass_g', 'island', 'sex'])

In [100]:
df

    species  bill_length_mm  flipper_length_mm
0    Adelie            39.1              181.0
1    Adelie            39.5              186.0
2    Adelie            40.3              195.0
3    Adelie             NaN                NaN
4    Adelie            36.7              193.0
..      ...             ...                ...
339  Gentoo             NaN                NaN
340  Gentoo            46.8              215.0
341  Gentoo            50.4              222.0
342  Gentoo            45.2              212.0
343  Gentoo            49.9              213.0

[344 rows x 3 columns]

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   bill_length_mm     342 non-null    float64
 2   flipper_length_mm  342 non-null    float64
dtypes: float64(2), object(1)
memory usage: 8.2+ KB

In [102]:
df.dropna()

    species  bill_length_mm  flipper_length_mm
0    Adelie            39.1              181.0
1    Adelie            39.5              186.0
2    Adelie            40.3              195.0
4    Adelie            36.7              193.0
5    Adelie            39.3              190.0
..      ...             ...                ...
338  Gentoo            47.2              214.0
340  Gentoo            46.8              215.0
341  Gentoo            50.4              222.0
342  Gentoo            45.2              212.0
343  Gentoo            49.9              213.0

[342 rows x 3 columns]

In [103]:
#NOTE: One hot label encoding
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [104]:
df['species'] = encoder.fit_transform(df['species'])
df['species']

0      0
1      0
2      0
3      0
4      0
      ..
339    2
340    2
341    2
342    2
343    2
Name: species, Length: 344, dtype: int64

In [105]:
df.head()

   species  bill_length_mm  flipper_length_mm
0        0            39.1              181.0
1        0            39.5              186.0
2        0            40.3              195.0
3        0             NaN                NaN
4        0            36.7              193.0

In [106]:
df = df.dropna()
df.head(10)

    species  bill_length_mm  flipper_length_mm
0         0            39.1              181.0
1         0            39.5              186.0
2         0            40.3              195.0
4         0            36.7              193.0
5         0            39.3              190.0
6         0            38.9              181.0
7         0            39.2              195.0
8         0            34.1              193.0
9         0            42.0              190.0
10        0            37.8              186.0

In [107]:
X = df.iloc[:,1:]
Y = df.iloc[:, 0:1]

In [124]:
Y.shape

(342, 1)

In [113]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(multi_class='multinomial')  #NOTE : since softmax so multinomial

In [114]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=41)

In [115]:
LR.fit(X_train,Y_train)

/Users/bheshu/Desktop/Machine Learning/ML_ENV/lib/python3.10/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/bheshu/Desktop/Machine Learning/ML_ENV/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/bheshu/Desktop/Machine Learning/ML_ENV/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(multi_class='multinomial')

In [116]:
pred_y = LR.predict(X_test)

In [117]:
#NOTE: metrics
from sklearn.metrics import accuracy_score

In [118]:
print(f"Accuracy of the model is : {accuracy_score(Y_test,pred_y)}")

Accuracy of the model is : 0.927536231884058

In [119]:
z = np.array([[3.4, 2.7]])      #NOTE: random points 
LR.predict_proba(z)     #NOTE : predicting probability using softmax funciton

/Users/bheshu/Desktop/Machine Learning/ML_ENV/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[1.00000000e+00, 3.02337196e-16, 1.70213633e-48]])

In [120]:
LR.predict(z)

/Users/bheshu/Desktop/Machine Learning/ML_ENV/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
#NOTE: array[0] means the probability of penguins being adele is more so for that random
# bill_length_mm and flipper_length_mm it is found that the penguin will be of Adelle species

# Predicting for other values of bill_length and flipper_length

In [137]:
input = np.array([[47.5, 217]])
prediction = LR.predict_proba(input)

if prediction[0][0] > prediction[0][1] and prediction[0][0] > prediction[0][2] : 
    print("The preguins is of Adelie species")
elif prediction[0][1] > prediction[0][0] and prediction[0][1] > prediction[0][2]:
    print("The preguins is of Chinstrap species")
else:
    print("The preguins is of Gentoo species")

The preguins is of Gentoo species

/Users/bheshu/Desktop/Machine Learning/ML_ENV/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(