In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IMDB Dataset.csv')
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [4]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

# NOTE: Text cleaning

In [5]:

df.iloc[0:1, :]

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive

In [6]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [7]:
df['review'][15]     #NOTE :here we. can see html tags so now we need to remove this shit !

"Kind of drawn in by the erotic scenes, only to realize this was one of the most amateurish and unbelievable bits of film I've ever seen. Sort of like a high school film project. What was Rosanna Arquette thinking?? And what was with all those stock characters in that bizarre supposed Midwest town? Pretty hard to get involved with this one. No lessons to be learned from it, no brilliant insights, just stilted and quite ridiculous (but lots of skin, if that intrigues you) videotaped nonsense....What was with the bisexual relationship, out of nowhere, after all the heterosexual encounters. And what was with that absurd dance, with everybody playing their stereotyped roles? Give this one a pass, it's like a million other miles of bad, wasted film, money that could have been spent on starving children or Aids in Africa....."

In [8]:
# NOTE: Removing html tags using regex 
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[1].review)    # removed all the html tags of row no 2 (index 1)

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [9]:
# NOTE : here i will remove now for all 50000 rows
def clean_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [10]:
# NOTE: callign above funciton
df['review'] = df['review'].apply(clean_tags)
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [11]:
# NOTE : creating special character remover function
def special_char(text):
    x = ''
    for word in text:
        if word.isalnum():
            x = x + word
        else:
            x = x + ' '     #put space if it is special characters
    return x

In [12]:
#NOTE : calling above function initially for one test 
special_char('Raji@v# is a G*&^d Boy')

'Raji v  is a G   d Boy'

In [13]:
# NOTE : Now i will call this for whole review rows 
df['review'] = df['review'].apply(special_char)
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production  The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there s a family where a little boy ...
4        Petter Mattei s  Love in the Time of Money  is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot  bad dialogue  bad acting  idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I m going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [14]:
#NOTE : making lower case 
def lower_case(text):
    return text.lower()

In [15]:
df['review'] = df['review'].apply(lower_case)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production  the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there s a family where a little boy ...  negative
4      petter mattei s  love in the time of money  is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot  bad dialogue  bad acting  idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i m going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [16]:
#NOTE : Removing all stops words like is , are , has , have etc.
import nltk     #nltk : natural language toolkit
from nltk.corpus import stopwords
nltk.download('stopwords')          #requires for first time

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/bheshu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
stopwords = stopwords.words('english')

In [18]:
def Eng_stopwords_counts(words):
    count = 0
    for i in words: #Note ; words is list
        count = count + 1
    return count

In [19]:
Eng_stopwords_counts(stopwords)

198

In [20]:
print(type(df['review'][0]))

<class 'str'>

In [21]:
#NOTE : there are total 198 stop words in 'english' language we gonna use for our sentiment analysis
def remove_stopwords(reviews):
    review_list = []
    for word in reviews.split():

        if word not in stopwords:
            review_list.append(word)    # if not a stop word in the review row list then only keep
        
        temp_review_list = review_list[:]
    review_list.clear()
    return temp_review_list

In [22]:
#NOTE :calling above funciton : to remove stop words from all 50000 rows of review
df['review'] = df['review'].apply(remove_stopwords)
df

                                                  review sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...  positive
1      [wonderful, little, production, filming, techn...  positive
2      [thought, wonderful, way, spend, time, hot, su...  positive
3      [basically, family, little, boy, jake, thinks,...  negative
4      [petter, mattei, love, time, money, visually, ...  positive
...                                                  ...       ...
49995  [thought, movie, right, good, job, creative, o...  positive
49996  [bad, plot, bad, dialogue, bad, acting, idioti...  negative
49997  [catholic, taught, parochial, elementary, scho...  negative
49998  [going, disagree, previous, comment, side, mal...  negative
49999  [one, expects, star, trek, movies, high, art, ...  negative

[50000 rows x 2 columns]

In [23]:
#NOTE: replacing positive with 1 and negative with 0
df['sentiment'].replace({
    'positive' : 1,
    'negative' : 0
},inplace=True)

/var/folders/jf/8ft3n5497pn97syqdww0k3gr0000gn/T/ipykernel_36710/1556745492.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({
/var/folders/jf/8ft3n5497pn97syqdww0k3gr0000gn/T/ipykernel_36710/1556745492.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({

In [24]:
df

                                                  review  sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...          1
1      [wonderful, little, production, filming, techn...          1
2      [thought, wonderful, way, spend, time, hot, su...          1
3      [basically, family, little, boy, jake, thinks,...          0
4      [petter, mattei, love, time, money, visually, ...          1
...                                                  ...        ...
49995  [thought, movie, right, good, job, creative, o...          1
49996  [bad, plot, bad, dialogue, bad, acting, idioti...          0
49997  [catholic, taught, parochial, elementary, scho...          0
49998  [going, disagree, previous, comment, side, mal...          0
49999  [one, expects, star, trek, movies, high, art, ...          0

[50000 rows x 2 columns]

In [25]:
#NOTE :performing stemming using count_vectorizer()
from nltk.stem.porter import PorterStemmer
PS = PorterStemmer()    # calling the function

In [26]:
row = []
def word_stemmer(reviews_row):
    for word in reviews_row:
        row.append(PS.stem(word))   # only storing stem words in each review list
    temp_list = row[:]
    row.clear()
    return temp_list

In [27]:
#NOTE: testing above function for single sentence
word_stemmer(['I', 'love', 'being', 'loved', 'by', 'everyone'])

['i', 'love', 'be', 'love', 'by', 'everyon']

In [28]:
word_stemmer(['playing', 'eating', 'scoring'])

['play', 'eat', 'score']

In [29]:
#NOTE: Now running word stemmer funciton for all reviews
df['review'] = df['review'].apply(word_stemmer)
df

                                                  review  sentiment
0      [one, review, mention, watch, 1, oz, episod, h...          1
1      [wonder, littl, product, film, techniqu, unass...          1
2      [thought, wonder, way, spend, time, hot, summe...          1
3      [basic, famili, littl, boy, jake, think, zombi...          0
4      [petter, mattei, love, time, money, visual, st...          1
...                                                  ...        ...
49995  [thought, movi, right, good, job, creativ, ori...          1
49996  [bad, plot, bad, dialogu, bad, act, idiot, dir...          0
49997  [cathol, taught, parochi, elementari, school, ...          0
49998  [go, disagre, previou, comment, side, maltin, ...          0
49999  [one, expect, star, trek, movi, high, art, fan...          0

[50000 rows x 2 columns]

In [30]:
#NOTE : now converting datatype of each review from list to string (sentence)
df['review'] = df['review'].apply(lambda row: " ".join(row))

In [31]:
df['review'][0]

'one review mention watch 1 oz episod hook right exactli happen first thing struck oz brutal unflinch scene violenc set right word go trust show faint heart timid show pull punch regard drug sex violenc hardcor classic use word call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda em citi home mani aryan muslim gangsta latino christian italian irish scuffl death stare dodgi deal shadi agreement never far away would say main appeal show due fact goe show dare forget pretti pictur paint mainstream audienc forget charm forget romanc oz mess around first episod ever saw struck nasti surreal say readi watch develop tast oz got accustom high level graphic violenc violenc injustic crook guard sold nickel inmat kill order get away well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom comfort uncomfort view that get touch darker side'

In [32]:
df

                                                  review  sentiment
0      one review mention watch 1 oz episod hook righ...          1
1      wonder littl product film techniqu unassum old...          1
2      thought wonder way spend time hot summer weeke...          1
3      basic famili littl boy jake think zombi closet...          0
4      petter mattei love time money visual stun film...          1
...                                                  ...        ...
49995  thought movi right good job creativ origin fir...          1
49996  bad plot bad dialogu bad act idiot direct anno...          0
49997  cathol taught parochi elementari school nun ta...          0
49998  go disagre previou comment side maltin one sec...          0
49999  one expect star trek movi high art fan expect ...          0

[50000 rows x 2 columns]

# NOTE: text cleaning all completed

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)         # words which are repeated atleast 1000 times

In [34]:
X = cv.fit_transform(df['review']).toarray()

In [35]:
X       #NOTE: this has 50000 rows and 1000 unique words in review

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(50000, 1000))

In [36]:
X.mean()        #NOTE: most of the words are repeated so mean is almost equal to 0

np.float64(0.07889406)

In [37]:
#NOTE : Y = (sentiments)
Y = df.iloc[:, -1].values

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.2)

In [39]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB

Model_Gauss = GaussianNB()
Model_Bernauli = BernoulliNB()
Model_Multi = MultinomialNB()

In [40]:
#NOTE: Training sets

Model_Gauss.fit(X_train, Y_train)
Model_Bernauli.fit(X_train, Y_train)
Model_Multi.fit(X_train, Y_train)

MultinomialNB()

In [41]:
#NOTE: Predicting sentiments [Testing Phase]
pred_sentiments_Gauss = Model_Gauss.predict(X_test)
pred_sentiments_Bernauli = Model_Bernauli.predict(X_test)
pred_sentiments_Multi = Model_Multi.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
print(f"The accuracy of Gaussian Model is {accuracy_score(Y_test,pred_sentiments_Gauss)}")
print(f"The accuracy of Bernauli model is : {accuracy_score(Y_test,pred_sentiments_Bernauli)}")
print(f"The accuracy of Multinomial model is {accuracy_score(Y_test,pred_sentiments_Multi)}")

The accuracy of Gaussian Model is 0.7819
The accuracy of Bernauli model is : 0.8305
The accuracy of Multinomial model is 0.8262